---
title: "lesson4"
author: "Wonjun Lee"
date: "May 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scatter Plots
```{r}
library(ggplot2)
pf <- read.csv('c:/users/WONJUN/dropbox/private/study/udacity/r_project/pseudo_facebook.tsv', sep = '\t')
names(pf)

ggplot(aes(x=age, y = friend_count), data = pf) +
  geom_point(alpha = 1/20, position = position_jitter(h = 0)) +
  coord_trans(y = "sqrt") +
  xlim(13, 90)
  
```

## Alpha and Jitter
```{r}
names(pf)
ggplot(aes(x=age, y = friendships_initiated), data = pf) +
  geom_point(alpha = 1/20, position = position_jitter(h=0)) +
  xlim(13, 90) +
  coord_trans(y = "sqrt")
```

## Conditional Means
```{r}
#install.packages('dplyr')
library(dplyr)

age_groups <- group_by(pf, age)
pf.fc_by_age <- summarise(age_groups,
                          friend_count_mean = mean(friend_count),
                          friend_count_mean = median(friend_count),
                          n=n())

pf.fc_by_age <- arrange(pf.fc_by_age, age)
head(pf.fc_by_age)

pf.fc_by_age <- pf %>%
  group_by(age) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  arrange(age)
pf.fc_by_age

ggplot(aes(x=age, y=friend_count_mean), data=pf.fc_by_age) +
  geom_line()
```

## Overlaying Summaries with Raw Data
```{r}
ggplot(aes(x=age, y=friend_count), data=pf) +
  xlim(13,90) +
  geom_point(alpha=0.05,
             position=position_jitter(h=0),
             color='orange') +
  coord_trans(y='sqrt') +
  geom_line(stat = 'summary', fun.y = mean) +
  geom_line(linetype = 2, color = 'blue', stat = 'summary', fun.y = quantile, fun.args= list(probs =.1)) +
  geom_line(linetype = 2, color = 'blue', stat = 'summary', fun.y = quantile, fun.args= list(probs =.9)) +
  geom_line(linetype = 2, color = 'blue', stat = 'summary', fun.y = quantile, fun.args= list(probs =.5))
  
```

## Correlation
```{r}
cor.test(pf$age,pf$friend_count, method='pearson')

with(pf, cor.test(age, friend_count, method = 'pearson'))

with(pf, cor.test(www_likes_received, likes_received, method = 'pearson'))
```

## Noisy Scatterplots
```{r}
#install.packages('alr3')
library(alr3)
data(Mitchell)

cor.test(Mitchell$Month, Mitchell$Temp)
```

## A New Perspective
```{r}
ggplot(data = Mitchell, aes(x = Month, y = Temp)) +
  geom_point(alpha = .2) +
  scale_x_continuous(breaks = seq(0,203,12))
```

## Create an age_with_months variable
```{r}
pf$age_with_months <- pf$age + (1-pf$dob_month/12)
```