Lesson 3
=====================================

## Reading in Data
```{r}
list.files()
pf <- read.csv('C:/users/wlee/dropbox/private/study/udacity/R_project/pseudo_facebook.tsv', sep='\t')
names(pf)
```

## Histogram of Users' Birthdays
```{r}
install.packages('ggplot2')
library(ggplot2)
names(pf)
ggplot(aes(x = dob_day), data=pf) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = 1:31)

```

## Faceting
```{r}
ggplot(aes(x=dob_day), data = pf) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = 1:31) +
  facet_wrap(~dob_month)
```
## Friend Count
```{r}
ggplot(aes(x=friend_count), data = pf) +
  geom_histogram(binwidth = 25) +
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000,50)) +
  facet_wrap(~gender)

```

## Omitting NA Gender Observations
```{r}
ggplot(aes(x=friend_count), data = subset(pf, !is.na(gender))) +
  geom_histogram() +
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000,50)) +
  facet_wrap(~gender)
```

## Statistics by Gender
```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```

## Tenure
```{r}
ggplot(aes(x=tenure), data = pf) +
  geom_histogram(binwidth = 30, color = 'black', fill = '#099DD9')

ggplot(aes(x=tenure/365), data = pf) +
  geom_histogram(binwidth = .25, color = 'black', fill = '#099DD9')

summary(pf$tenure)
```

## Labeling Plots
```{r}
ggplot(aes(x = tenure/365), data = pf) +
  geom_histogram(color = 'black', fill = '#F79420') +
  scale_x_continuous(breaks = seq(1,7,1), limits = c(0,7)) +
  xlab('Number of years using Facebook') +
  ylab('Number of users in sample')
```

## Users Ages
```{r}
ggplot(aes(x = age), data = pf) +
  geom_histogram(binwidth = 1,color='black', fill = '#5760AB') +
  scale_x_continuous(breaks = seq(0,113,5))  
```

## Transforming Data
```{r}
ggplot(aes(x = friend_count), data = pf) +
  geom_histogram()

summary(pf$friend_count)
summary(log10(pf$friend_count+1))
summary(sqrt(pf$friend_count))

install.packages('gridExtra')
library(gridExtra)


friendCount <- ggplot(aes(x = friend_count), data = pf) +
  geom_histogram()
log10friendCount <- ggplot(aes(x = log10(friend_count+1)), data = pf) + 
  geom_histogram()
sqrtfriendCount <- ggplot(aes(x = sqrt(friend_count)), data = pf) + 
  geom_histogram()

grid.arrange(friendCount, log10friendCount, sqrtfriendCount, ncol = 1)
```

## Using better method
```{r}
p1 <- ggplot(aes(x = friend_count), data = pf) + geom_histogram()
p2 <- p1 + scale_x_log10()
p3 <- p1 + scale_x_sqrt()

grid.arrange(p1,p2,p3, ncol = 1)
```

## Add a Scaling Layer
```{r}
logScale <- ggplot(aes(x = log10(friend_count)), data = pf) +
  geom_histogram()

countScale <- ggplot(aes(x = friend_count), data =pf) +
  geom_histogram() +
  scale_x_log10()

grid.arrange(logScale, countScale, ncol = 2)
```

## Frequency Polygons (before we had historgrams)
```{r}
ggplot(aes(x = friend_count), data = subset(pf, !is.na(gender))) +
  geom_histogram(binwidth = 10) +
  scale_x_continuous(lim = c(0,1000), breaks = seq(0,1000,50)) +
  facet_wrap(~gender)

ggplot(aes(x = friend_count, y = ..count../sum(..count..)), data = subset(pf,!is.na(gender))) +
  geom_freqpoly(aes(color = gender), binwidth = 10) +
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000,50)) +
  xlab('Friend Count') +
  ylab('Percentage of users with that friend count')

ggplot(aes(x = www_likes), data = subset(pf, !is.na(gender))) +
  geom_freqpoly(aes(color= gender)) +
  #scale_x_continuous() +
  scale_x_log10()
```

### Likes on the Web
```{r}
summary(pf$www_likes)
by(pf$www_likes, pf$gender, median)
```

## Box Plots
```{r}
ggplot(aes(x=gender, y = friend_count), data = subset(pf,!is.na(gender))) +
  geom_boxplot()

ggplot(aes(x=gender, y=friend_count), data=subset(pf,!is.na(gender))) +
  geom_boxplot() +
  scale_y_continuous(limits=c(0,1000))

ggplot(aes(x=gender, y=friend_count), data=subset(pf,!is.na(gender))) +
  geom_boxplot() +
  coord_cartesian(ylim=c(0,250))

by(pf$friend_count, pf$gender, summary)
```

## Getting Logical
```{r}
summary(pf$mobile_likes)
summary(pf$mobile_likes>0)
pf$mobile_check_in <- ifelse(pf$mobile_likes>0,1,0)
pf$mobile_likes <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
```

