Problem Set 2
=====================================

## Importing Data
```{r}
install.packages(ggplot2)
library(ggplot2)
data(diamonds)

names(diamonds)
```

## Price vs. x
```{r}
ggplot(aes(x=price, y=x), data=diamonds) +
  geom_point()
```

## Correlation
```{r}
cor.test(diamonds$price, diamonds$x)
cor.test(diamonds$price, diamonds$y)
cor.test(diamonds$price, diamonds$z)
```

## Price vs. Depth
```{r}
ggplot(data = diamonds, aes(x = depth, y = price)) + 
  geom_point(alpha=1/100)
```

## Correlation
```{r}
cor.test(diamonds$depth, diamonds$price)
```

## Price vs. Carat
```{r}
ggplot(aes(x=price,y=carat), data=diamonds) +
  geom_point()
```

## Prics vs. Volume
```{r}
diamonds$volume = diamonds$x * diamonds$y * diamonds$z
ggplot(aes(x=price, y=volume), data=diamonds) +
  geom_point()
```

## Correlation
```{r}
cor.test(diamonds$volume[diamonds$volume>0 & diamonds$volume<800], diamonds$price[diamonds$volume>0 & diamonds$volume<800])
```

## Subsetting
```{r}
ggplot(aes(x=price, y=volume), data=subset(diamonds,diamonds$volume>0 & diamonds$volume<800)) +
  geom_point()
```

## Using dply library
```{r}
install.packages('dplyr')
library(dplyr)
diamondsByClarity <- diamonds %>%
  group_by(clarity) %>%
  summarise(mean_price = mean(price),
            median_price = median(price),
            min_price = min(price),
            max_price = max(price),
            n = n())


```

## By Clarity
```{r}
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))
diamonds_mp_by_clarity
  library(gridExtra)

p1 <- ggplot(aes(x=clarity,y=mean_price), data=diamonds_mp_by_clarity) +
  geom_bar(stat="identity")

p2 <- ggplot(aes(x=color,y=mean_price), data=diamonds_mp_by_color) +
  geom_bar(stat="identity")

grid.arrange(p1,p2, ncol =2)
```

