## Import Yogurt Data
```{r}
pf <- read.csv('c:/users/YURI/documents/wonjunee/udacity/data-analysis-with-R/pseudo_facebook.tsv', sep = '\t')
pf <- read.csv('c:/users/wlee/dropbox/private/study/udacity/r_project/pseudo_facebook.tsv', sep = '\t')

yo <- read.csv('c:/users/YURI/documents/wonjunee/udacity/data-analysis-with-R/yogurt.csv', sep = ',')
yo <- read.csv('c:/users/wlee/dropbox/private/study/udacity/r_project/yogurt.csv', sep = ',')
```

## Adding columns
```{r}
install.packages(dplyr)
library(dplyr)
pf.fc_by_age_gender <- pf %>%
    group_by(age,gender) %>%
    summarise(mean_friend_count=mean(friend_count), median_friend_count=median(friend_count),n=n())

pf.fc_by_age_gender <-subset(pf.fc_by_age_gender,!is.na(pf.fc_by_age_gender$gender))

names(pf)
```

## Histograms
```{r}
library(ggplot2)
ggplot(aes(x=price), data=yo) +
  geom_histogram(aes(fill=I('#F79420')))

ggplot(aes(x=price), data=yo) +
  geom_histogram(binwidth=10,aes(fill=I('#F79420')))
```

## Number of Purchases
```{r}
summary(yo)
length(unique(yo$price))
table(yo$price)
str(yo)
yo <-transform(yo, all.purchases = strawberry+blueberry+pina.colada+plain+mixed.berry)

yo$all.purchases

```

## Histogram
```{r}
ggplot(aes(x=all.purchases), data=yo) +
  geom_histogram(binwidth=1, aes(fill=I('#099DD9')))
```

## Prices over Time Solution
```{r}
ggplot(aes(x=time,y=price), data=yo) +
  geom_jitter(alpha=1/4, shape=21, fill=I('#F79420'))
```

## Looking at Samples of Households
```{r}
set.seed(4000)
yo$id
sample.ids <- sample(yo$id, 16)
sample.ids
ggplot(aes(x=time,y=price),
       data=subset(yo,id %in% sample.ids)) +
  facet_wrap(~id) +
  geom_line() +
  geom_point(aes(size=all.purchases), pch = 1)
  
# Need to analyze more and upload it to a discussion board.
```

## Scatterplot Matrices
```{r}
install.packages("GGally")
library(GGally)
theme_set(theme_minimal(20))

# set the seed for reproducible results
set.seed(1836)
pf_subset <- pf[, c(2:15)]
names(pf_subset)
ggpairs(pf_subset[sample.int(nrow(pf_subset),1000),])

```




