Problem Set 1
==================================
## loading diamonds data set
```{r}
install.packages(ggplot2)
library(ggplot2)
data(diamonds)
summary(diamonds)
length(diamonds$price)
names(diamonds)
ggplot(aes(x = price), data=diamonds) +
  geom_histogram()
?diamonds
summary(diamonds$price<500)
summary(diamonds$price<250)
summary(diamonds$price>=15000)
```

## Cheaper Diamonds
```{r}
ggplot(aes(x=price),data=diamonds) +
  geom_histogram( breaks=seq(0,20000,200)) +
  facet_wrap(~cut)
```

## Price per Carat by Cut
```{r}
ggplot(aes(x=price),data=diamonds) +
  geom_histogram( breaks=seq(0,20000,200)) +
  scale_x_log10()
  facet_wrap(~cut)
```

## Price Box Plots
```{r}
ggplot(aes(x=cut, y=price),data=diamonds) +
  geom_boxplot()
ggplot(aes(x=clarity, y=price),data=diamonds) +
  geom_boxplot()
ggplot(aes(x=color, y=price),data=diamonds) +
  geom_boxplot()
```
## Interquartile Range
```{r}
subset(by(diamonds$price, diamonds$carat, length),by(diamonds$price, diamonds$carat, length)>2000)
```
## How many people sharing my birthday
```{r}
pf <- read.csv('C:/users/WONJUN/dropbox/private/study/udacity/R_project/pseudo_facebook.tsv', sep='\t')
names(pf)

myBirthday <- subset(pf, dob_day == 24 & dob_month == 2)
summary(myBirthday)
```


